version: '3.8'
# https://docs.docker.com/compose/yml/

services:
  apis:
    container_name: api_c
    restart: always
    build: ./api
    # Each service defined in docker-compose.yml must specify exactly one of
    # image or build. Other keys are optional, and are analogous to their
    # docker run command-line counterparts.
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo_c
    image: mongo
    volumes:
      - ./../data:/data/db
    # all of the volumes. 
    ports:
      - '27017:27017'
  frontend:
    build: ./frontend
    # Each service defined in docker-compose.yml must specify exactly one of
    # image or build. 
    container_name: frontend_c
    command: npm start
    volumes:
      - '.:/frontend/react'
      - '/frontend/react/node_modules'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true